name: ItemsBorder
version: '0.1'
main: com.protoser.itemsBorder.ItemsBorder
api-version: '1.21'
authors: [ Protoser ]
description: Custom Solution for Project Management
website: https://protoser.com
