name: ItemsBorder
version: '1.2'
main: com.protoser.itemsBorder.ItemsBorder
api-version: '1.21'
authors: [ Protoser ]
description: Custom Solution for Project Management
website: https://protoser.com
commands:
  items:
    description: Opens a GUI displaying all items.
    usage: /items